import tensorflow as tf
import numpy as np

def verify_tflite_quantization(tflite_model_path):
    """
    Loads a .tflite FlatBuffer and iterates through its computational graph 
    to verify the data types and quantization parameters of the weight tensors.
    """
    print(f"Loading and analyzing TFLite model: {tflite_model_path}\n")
    
    # 1. Initialize the Interpreter and allocate memory for the model's tensors
    interpreter = tf.lite.Interpreter(model_path=tflite_model_path)
    interpreter.allocate_tensors()
    
    # 2. Extract the dictionary of properties for every tensor in the graph
    tensor_details = interpreter.get_tensor_details()
    
    int4_verified = True
    
    # 3. Iterate over the network to inspect the parameters
    for tensor in tensor_details:
        name = tensor['name']
        dtype = tensor['dtype']
        quantization_params = tensor['quantization']
        
        # We isolate the weight matrices (kernels/filters) used in Conv and Dense layers.
        # Biases and activations frequently follow different quantization rules (e.g., INT32 or INT8).
        if 'weight' in name.lower() or 'kernel' in name.lower() or 'conv' in name.lower():
            print(f"Layer Tensor: {name}")
            print(f"  - Stored Data Type: {dtype}")
            print(f"  - Quantization Info (Scale, Zero Point): {quantization_params}")
            
            # Extract the actual weight array to verify its numerical bounds
            weight_array = interpreter.get_tensor(tensor['index'])
            min_val, max_val = np.min(weight_array), np.max(weight_array)
            print(f"  - Empirical Range: [{min_val}, {max_val}]")
            
            # INT4 precision natively spans [-8, 7].
            # Note: Standard TFLite frequently stores 4-bit quantized values within an 8-bit (INT8) 
            # storage container to maintain byte-alignment compatibility with standard memory.
            if dtype == np.int8 and min_val >= -8 and max_val <= 7:
                print("  => VERIFIED: Weights are constrained to 4-bit (INT4) precision.\n")
            else:
                print("  => WARNING: Precision bounds exceed INT4 constraints.\n")
                int4_verified = False

    if int4_verified:
        print("Model verification complete. All inspected weights meet 4-bit quantization constraints.")
    else:
        print("Model verification complete. Some tensors exceed target precision.")

if __name__ == "__main__":
    # Point this to the FlatBuffer generated by main.py 
    model_path = "model_full.tflite"
    verify_tflite_quantization(model_path)
